-- AI CRM 任务表
CREATE TABLE IF NOT EXISTS `aicrm_task` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '任务ID',
  `task_type` varchar(50) NOT NULL COMMENT '任务类型（ASSET_UPGRADE-资产提升、EXPIRE_REMINDER-到期提醒、COMPLIANCE-合规、MEETING-会议、ADMINISTRATIVE-行政、OTHER-其他）',
  `title` varchar(255) NOT NULL COMMENT '任务标题',
  `description` text COMMENT '任务描述',
  `priority` varchar(20) NOT NULL COMMENT '优先级（P0-紧急、P1-重要、P2-普通、P3-低优先级）',
  `comprehensive_score` decimal(3,1) DEFAULT '0.0' COMMENT '综合评分 (0-10)',
  `category` varchar(100) COMMENT '任务分类',
  `customer_id` bigint COMMENT '客户ID',
  `customer_name` varchar(100) COMMENT '客户姓名',
  `deadline` datetime COMMENT '截止时间',
  `completed_time` datetime COMMENT '完成时间',
  `business_value` varchar(20) COMMENT '业务价值等级 (high/medium/low)',
  `expected_revenue` decimal(15,2) COMMENT '预期收益（元）',
  `status` tinyint NOT NULL DEFAULT '0' COMMENT '任务状态（0=待办 1=进行中 2=已完成 3=已取消）',
  `ai_generated` tinyint NOT NULL DEFAULT '0' COMMENT '是否AI生成（0=否 1=是）',
  `ai_reason` text COMMENT 'AI生成原因',
  `ai_suggestion` text COMMENT 'AI建议',
  `trigger_source` varchar(100) COMMENT '触发来源',
  `is_urgent` tinyint NOT NULL DEFAULT '0' COMMENT '是否紧急（0=否 1=是）',
  `creator` varchar(64) DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  `tenant_id` bigint NOT NULL DEFAULT '0' COMMENT '租户编号',
  PRIMARY KEY (`id`),
  KEY `idx_customer_id` (`customer_id`),
  KEY `idx_status` (`status`),
  KEY `idx_deadline` (`deadline`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='AI CRM 任务表';
