-- 社区信息表
CREATE TABLE IF NOT EXISTS `grid_community_info` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `community_code` VARCHAR(50) NOT NULL COMMENT '社区编号',
    `community_name` VARCHAR(100) NOT NULL COMMENT '社区名称',
    `team_count` INT DEFAULT 0 COMMENT '团队人数',
    `manager_user_id` BIGINT COMMENT '责任人工号（关联system_users.id）',
    `manager_user_name` VARCHAR(50) COMMENT '责任人姓名',
    `household_count` INT DEFAULT 0 COMMENT '人口（户数）',
    `individual_business_count` INT DEFAULT 0 COMMENT '个体工商户数',
    `small_enterprise_count` INT DEFAULT 0 COMMENT '小微企业数',
    `commercial_complex_count` INT DEFAULT 0 COMMENT '商业综合体数',
    `quality_unit_count` INT DEFAULT 0 COMMENT '优质单位数',
    `score` DECIMAL(10,2) DEFAULT 0.00 COMMENT '评分',
    `adjusted_score` DECIMAL(10,2) DEFAULT 0.00 COMMENT '校正评分',
    `adjustment_reason` VARCHAR(500) COMMENT '校正原因',
    `status` VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态（ACTIVE=正常，INACTIVE=无效）',
    `creator` VARCHAR(64) DEFAULT '' COMMENT '创建者',
    `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `updater` VARCHAR(64) DEFAULT '' COMMENT '更新者',
    `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `deleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
    `tenant_id` BIGINT NOT NULL DEFAULT 0 COMMENT '租户编号',
    PRIMARY KEY (`id`),
    KEY `idx_community_code` (`community_code`),
    KEY `idx_community_name` (`community_name`),
    KEY `idx_manager_user_id` (`manager_user_id`),
    KEY `idx_tenant_id` (`tenant_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='社区信息表';
