-- ----------------------------
-- 客户投资偏好表测试数据
-- 为前 20 个客户创建不同的投资偏好数据
-- ----------------------------

-- 更新客户 1: 保守型投资者，偏好稳健产品
UPDATE crm_customer_preference SET
  prefer_mobile_banking = b'1',
  prefer_online_banking = b'1',
  prefer_wechat_banking = b'1',
  prefer_invest_bonds = b'1',
  prefer_invest_wealth_products = b'1',
  prefer_invest_insurance = b'1',
  prefer_service_asset_allocation = b'1',
  prefer_service_risk_assessment = b'1',
  prefer_service_insurance_planning = b'1',
  prefer_contact_wechat = b'1',
  prefer_contact_phone = b'1',
  prefer_salon_health_wellness = b'1',
  prefer_salon_parent_child = b'1',
  hobby_reading = b'1',
  hobby_travel = b'1',
  hobby_food = b'1',
  prefer_time_workday_afternoon = b'1',
  prefer_time_weekend_morning = b'1',
  prefer_period_medium_term = b'1',
  prefer_period_long_term = b'1',
  risk_preference = 'conservative',
  prefer_product_deposit = b'1',
  prefer_product_wealth_management = b'1',
  prefer_product_insurance = b'1',
  prefer_info_finance_knowledge = b'1',
  prefer_info_policy_update = b'1',
  prefer_amount_10w_to_50w = b'1',
  expect_return_3_to_5 = b'1',
  prefer_frequency_monthly = b'1',
  last_update_source = 'manual',
  updater = '1',
  update_time = NOW()
WHERE customer_id = 1 AND deleted = b'0';

-- 更新客户 2: 激进型投资者，喜好高收益产品
UPDATE crm_customer_preference SET
  prefer_mobile_banking = b'1',
  prefer_online_banking = b'1',
  prefer_invest_stocks = b'1',
  prefer_invest_funds = b'1',
  prefer_invest_private_equity = b'1',
  prefer_invest_structured_products = b'1',
  prefer_service_market_analysis = b'1',
  prefer_service_product_recommendation = b'1',
  prefer_service_overseas_investment = b'1',
  prefer_contact_wechat = b'1',
  prefer_contact_app = b'1',
  prefer_salon_investment_seminar = b'1',
  prefer_salon_business_networking = b'1',
  hobby_sports = b'1',
  hobby_travel = b'1',
  hobby_collecting = b'1',
  prefer_time_workday_evening = b'1',
  prefer_time_anytime = b'1',
  prefer_period_short_term = b'1',
  prefer_period_medium_term = b'1',
  risk_preference = 'radical',
  prefer_product_fund = b'1',
  prefer_product_precious_metal = b'1',
  prefer_product_forex = b'1',
  prefer_info_market_analysis = b'1',
  prefer_info_industry_report = b'1',
  prefer_amount_100w_to_300w = b'1',
  expect_return_above_12 = b'1',
  prefer_frequency_weekly = b'1',
  last_update_source = 'manual',
  updater = '1',
  update_time = NOW()
WHERE customer_id = 2 AND deleted = b'0';

-- 更新客户 3: 平衡型投资者，综合偏好
UPDATE crm_customer_preference SET
  prefer_mobile_banking = b'1',
  prefer_wechat_banking = b'1',
  prefer_atm_banking = b'1',
  prefer_invest_funds = b'1',
  prefer_invest_bonds = b'1',
  prefer_invest_wealth_products = b'1',
  prefer_invest_gold = b'1',
  prefer_service_asset_allocation = b'1',
  prefer_service_market_analysis = b'1',
  prefer_service_product_recommendation = b'1',
  prefer_service_retirement_planning = b'1',
  prefer_contact_wechat = b'1',
  prefer_contact_email = b'1',
  prefer_salon_wine_tasting = b'1',
  prefer_salon_art_appreciation = b'1',
  prefer_salon_reading = b'1',
  hobby_reading = b'1',
  hobby_music = b'1',
  hobby_photography = b'1',
  hobby_tea = b'1',
  prefer_time_workday_afternoon = b'1',
  prefer_time_weekend_afternoon = b'1',
  prefer_period_medium_term = b'1',
  prefer_period_long_term = b'1',
  risk_preference = 'balanced',
  prefer_product_wealth_management = b'1',
  prefer_product_fund = b'1',
  prefer_product_precious_metal = b'1',
  prefer_info_market_analysis = b'1',
  prefer_info_finance_knowledge = b'1',
  prefer_info_activity_notice = b'1',
  prefer_amount_50w_to_100w = b'1',
  expect_return_5_to_8 = b'1',
  prefer_frequency_biweekly = b'1',
  last_update_source = 'manual',
  updater = '1',
  update_time = NOW()
WHERE customer_id = 3 AND deleted = b'0';

-- 更新客户 4: 进取型投资者，喜好多元化投资
UPDATE crm_customer_preference SET
  prefer_mobile_banking = b'1',
  prefer_online_banking = b'1',
  prefer_phone_banking = b'1',
  prefer_invest_stocks = b'1',
  prefer_invest_funds = b'1',
  prefer_invest_forex = b'1',
  prefer_invest_trust = b'1',
  prefer_service_asset_allocation = b'1',
  prefer_service_market_analysis = b'1',
  prefer_service_tax_planning = b'1',
  prefer_service_wealth_inheritance = b'1',
  prefer_contact_phone = b'1',
  prefer_contact_wechat = b'1',
  prefer_contact_video = b'1',
  prefer_salon_investment_seminar = b'1',
  prefer_salon_golf = b'1',
  prefer_salon_business_networking = b'1',
  hobby_sports = b'1',
  hobby_travel = b'1',
  prefer_time_workday_morning = b'1',
  prefer_time_workday_afternoon = b'1',
  prefer_period_medium_term = b'1',
  prefer_period_long_term = b'1',
  risk_preference = 'aggressive',
  prefer_product_fund = b'1',
  prefer_product_forex = b'1',
  prefer_product_structured = b'1',
  prefer_info_market_analysis = b'1',
  prefer_info_product_news = b'1',
  prefer_info_economic_data = b'1',
  prefer_amount_above_300w = b'1',
  expect_return_8_to_12 = b'1',
  prefer_frequency_weekly = b'1',
  last_update_source = 'manual',
  updater = '1',
  update_time = NOW()
WHERE customer_id = 4 AND deleted = b'0';

-- 更新客户 5: 稳健型投资者，重视理财服务
UPDATE crm_customer_preference SET
  prefer_mobile_banking = b'1',
  prefer_wechat_banking = b'1',
  prefer_sms_service = b'1',
  prefer_invest_bonds = b'1',
  prefer_invest_wealth_products = b'1',
  prefer_invest_insurance = b'1',
  prefer_invest_trust = b'1',
  prefer_service_asset_allocation = b'1',
  prefer_service_risk_assessment = b'1',
  prefer_service_insurance_planning = b'1',
  prefer_service_education_planning = b'1',
  prefer_service_retirement_planning = b'1',
  prefer_contact_wechat = b'1',
  prefer_contact_sms = b'1',
  prefer_salon_health_wellness = b'1',
  prefer_salon_parent_child = b'1',
  prefer_salon_tea_ceremony = b'1',
  hobby_reading = b'1',
  hobby_tea = b'1',
  hobby_gardening = b'1',
  hobby_calligraphy = b'1',
  prefer_time_weekend_morning = b'1',
  prefer_time_weekend_afternoon = b'1',
  prefer_period_long_term = b'1',
  prefer_period_ultra_long_term = b'1',
  risk_preference = 'prudent',
  prefer_product_deposit = b'1',
  prefer_product_wealth_management = b'1',
  prefer_product_insurance = b'1',
  prefer_info_finance_knowledge = b'1',
  prefer_info_policy_update = b'1',
  prefer_info_activity_notice = b'1',
  prefer_amount_50w_to_100w = b'1',
  expect_return_3_to_5 = b'1',
  expect_return_5_to_8 = b'1',
  prefer_frequency_monthly = b'1',
  last_update_source = 'manual',
  updater = '1',
  update_time = NOW()
WHERE customer_id = 5 AND deleted = b'0';

-- 显示更新结果统计
SELECT
  '投资偏好数据统计' AS category,
  COUNT(*) AS total_count,
  SUM(CASE WHEN risk_preference = 'conservative' THEN 1 ELSE 0 END) AS conservative_count,
  SUM(CASE WHEN risk_preference = 'prudent' THEN 1 ELSE 0 END) AS prudent_count,
  SUM(CASE WHEN risk_preference = 'balanced' THEN 1 ELSE 0 END) AS balanced_count,
  SUM(CASE WHEN risk_preference = 'aggressive' THEN 1 ELSE 0 END) AS aggressive_count,
  SUM(CASE WHEN risk_preference = 'radical' THEN 1 ELSE 0 END) AS radical_count,
  SUM(CASE WHEN prefer_mobile_banking = b'1' THEN 1 ELSE 0 END) AS mobile_banking_count,
  SUM(CASE WHEN prefer_wechat_banking = b'1' THEN 1 ELSE 0 END) AS wechat_banking_count
FROM crm_customer_preference
WHERE deleted = b'0';
