// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-chat/internal/dao/internal"
)

// internalCustomerChatCollectInfoDao is internal type for wrapping internal DAO implements.
type internalCustomerChatCollectInfoDao = *internal.CustomerChatCollectInfoDao

// customerChatCollectInfoDao is the data access object for table customer_chat_collect_info.
// You can define custom methods on it to extend its functionality as you wish.
type customerChatCollectInfoDao struct {
	internalCustomerChatCollectInfoDao
}

var (
	// CustomerChatCollectInfo is globally public accessible object for table customer_chat_collect_info operations.
	CustomerChatCollectInfo = customerChatCollectInfoDao{
		internal.NewCustomerChatCollectInfoDao(),
	}
)

// Fill with you ideas below.
